# Generated by Django 4.0 on 2022-10-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usecase', models.CharField(help_text='Use Case', max_length=200, verbose_name='use_case')),
                ('description', models.CharField(help_text='Description', max_length=200, null=True, verbose_name='description')),
                ('default_syntax', models.CharField(help_text='default syntax', max_length=200, null=True, verbose_name='default_syntax')),
                ('category_rule', models.CharField(help_text='category_rule', max_length=200, null=True, verbose_name='category_rule')),
                ('subcategory_rule', models.CharField(help_text='subcategory rule', max_length=256, null=True, verbose_name='subcategory_rule')),
                ('correlation_rule', models.CharField(help_text='correlation rule', max_length=256, null=True, verbose_name='correlation_rule')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Rule Name', max_length=200, verbose_name='rule_name')),
                ('description', models.CharField(help_text='Description', max_length=200, verbose_name='description')),
                ('default', models.CharField(help_text='Default', max_length=200, verbose_name='default')),
                ('usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shared_stage.usecase', verbose_name='usecase')),
            ],
        ),
    ]
