# Generated by Django 4.0 on 2022-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='correlation_rule',
            field=models.CharField(help_text='correlation rule', max_length=500, null=True, verbose_name='correlation_rule'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='default_syntax',
            field=models.CharField(help_text='default syntax', max_length=2000, null=True, verbose_name='default_syntax'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='description',
            field=models.CharField(help_text='Description', max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='subcategory_rule',
            field=models.CharField(help_text='subcategory rule', max_length=500, null=True, verbose_name='subcategory_rule'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase',
            field=models.CharField(help_text='Use Case', max_length=500, verbose_name='use_case'),
        ),
    ]
