# Generated by Django 4.0 on 2022-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_stage', '0002_alter_usecase_correlation_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='default_syntax',
            field=models.CharField(help_text='default syntax', max_length=10000, null=True, verbose_name='default_syntax'),
        ),
    ]
