# Generated by Django 4.0 on 2022-10-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sita', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstg_itsm',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='entity_id',
            field=models.ForeignKey(help_text='entity_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sita.entity', verbose_name='entity_id'),
        ),
        migrations.AddField(
            model_name='function',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sita.geolocation', verbose_name='localtion_id'),
        ),
        migrations.AddField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(help_text='Asset Category', on_delete=django.db.models.deletion.CASCADE, to='sita.category'),
        ),
        migrations.AddField(
            model_name='assets',
            name='process_id',
            field=models.ForeignKey(help_text='Process Name', on_delete=django.db.models.deletion.CASCADE, to='sita.process', verbose_name='process_id'),
        ),
    ]
