# Generated by Django 4.0 on 2022-10-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Account',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Affair',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Answer_date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Applicant',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Application_Status',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Approval_Status',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Article',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Asset_Name',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Case_With_Manufacturer',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Child_CI_type',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Cluster',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Complexity',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Contract_start_date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='CreatedTime',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Created_by',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Ending_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Exchanged_Service',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Expiration_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Expired_status',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Fault_Neutralization_Date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='First_Responder_Status_Expired',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Hardware_Damage_Confirmation_Date_Manufacturer',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Impact',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Itsm_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Last_update_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Level',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Neutralization_SLA',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Onsite_care_date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Onsite_engineer_request_date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Onsite_service_SLA',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Opportunity_Status',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Pending_status',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_category',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_cvss_base',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_cvss_temporary',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_first_time_detected',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_group',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_impact',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_last_time_detected',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_last_time_tested',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_owasp',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_owasp_name',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_payload_method',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_payload_response',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_severity',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_solution',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_state',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Qualys_url',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='RCF',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='RequestID',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='RequestStatus',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='RequestType',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Request_Closure_Comments',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Request_closing_code',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Request_mode',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Resolution',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Resolution_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Response_due_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='SIEM_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='SLA_Service_time_for_remote_connection',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='SLA_Spare_Parts_Stock_Delivery_Time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='SLA_Stock_of_Spare_Parts',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='SOAR_ID',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Sale_order',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Sensor',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Site',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Solicitant_area',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Spare_Parts_Stock_Delivery_Date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Subcategory',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Technician',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Telephone_notification_date',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Time_elapsed',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='Urgency',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='User_On_Behalf_Of_OBO',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='VIP_user',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='assigned_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='false_positives',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='false_positives_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='first_response_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='first_response_time_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='group',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='number_of_services',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='reopened',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='reopened_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='resolved_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='response_time_id',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='service_category',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='sla_completion_time',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='target',
        ),
        migrations.RemoveField(
            model_name='stg_itsm',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='account_id',
            field=models.IntegerField(help_text='Account id', null=True, verbose_name='account_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='account_name',
            field=models.CharField(help_text='Account name', max_length=10000, null=True, verbose_name='account_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_billunclosed',
            field=models.BooleanField(help_text='Account contract bill unclosed', null=True, verbose_name='accountcontract_billunclosed'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_contractid',
            field=models.IntegerField(help_text='Account contract contract id', null=True, verbose_name='accountcontract_contractid'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_contractname',
            field=models.CharField(help_text='Account contract contract name', max_length=10000, null=True, verbose_name='accountcontract_contractname'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_contractnumber',
            field=models.CharField(help_text='Account contract contract number', max_length=10000, null=True, verbose_name='accountcontract_contractnumber'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_description',
            field=models.CharField(help_text='Account contract description', max_length=10000, null=True, verbose_name='accountcontract_description'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_isactivecontract',
            field=models.BooleanField(help_text='Account contract is active contract', null=True, verbose_name='accountcontract_isactivecontract'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='accountcontract_serviceplan_id',
            field=models.IntegerField(help_text='Account contract serviceplan id', null=True, verbose_name='accountcontract_serviceplan_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='approval_status',
            field=models.CharField(help_text='Approva Status', max_length=10000, null=True, verbose_name='approval_status'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='assets',
            field=models.CharField(help_text='Assets', max_length=10000, null=True, verbose_name='assets'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='assigned_time_display_value',
            field=models.DateTimeField(help_text='Assigned time display value', max_length=10000, null=True, verbose_name='assigned_time_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='assigned_time_value',
            field=models.CharField(help_text='Assigned time value', max_length=10000, null=True, verbose_name='assigned_time_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='billing_status_billingstatusid',
            field=models.IntegerField(help_text='Billing status billingstatusid', null=True, verbose_name='billing_status_billingstatusid'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='billing_status_billingstatusname',
            field=models.CharField(help_text='Billing Status Billing Status Name', max_length=10000, null=True, verbose_name='billing_status_billingstatusname'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='callback_url',
            field=models.CharField(help_text='Callback url', max_length=10000, null=True, verbose_name='callback_url'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='category_name',
            field=models.CharField(help_text='Category name', max_length=10000, null=True, verbose_name='category_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_closure_code',
            field=models.CharField(help_text='Closure info closure code', max_length=10000, null=True, verbose_name='closure_info_closure_code'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_closure_code_id',
            field=models.IntegerField(help_text='Closure info closure code id', null=True, verbose_name='closure_info_closure_code_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_closure_code_name',
            field=models.CharField(help_text='Closure info closure code name', max_length=10000, null=True, verbose_name='closure_info_closure_code_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_closure_comments',
            field=models.CharField(help_text='Closure info closure comments', max_length=10000, null=True, verbose_name='closure_info_closure_comments'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_requester_ack_comments',
            field=models.CharField(help_text='Closure info requester ack comments', max_length=10000, null=True, verbose_name='closure_info_requester_ack_comments'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_requester_ack_resolution',
            field=models.CharField(help_text='Closure info requester ack resolution', max_length=10000, null=True, verbose_name='closure_info_requester_ack_resolution'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='closure_info_signoff',
            field=models.CharField(help_text='Closure info signoff', max_length=10000, null=True, verbose_name='closure_info_signoff'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='completed_time_display_value',
            field=models.DateTimeField(help_text='Completed time display value', max_length=10000, null=True, verbose_name='completed_time_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='completed_time_value',
            field=models.CharField(help_text='Completed time value', max_length=10000, null=True, verbose_name='completed_time_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_by_email_id',
            field=models.CharField(help_text='Created By Email Id', max_length=10000, null=True, verbose_name='created_by_email_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_by_id',
            field=models.IntegerField(help_text='Created By id', null=True, verbose_name='created_by_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_by_is_vipuser',
            field=models.BooleanField(help_text='Created By is vipuser', null=True, verbose_name='created_by_is_vipuser'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_by_mobile',
            field=models.CharField(help_text='Created by Mobile', max_length=10000, null=True, verbose_name='created_by_mobile'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_by_name',
            field=models.CharField(help_text='Created By Name', max_length=10000, null=True, verbose_name='created_by_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_by_status',
            field=models.CharField(help_text='Created by status', max_length=10000, null=True, verbose_name='created_by_status'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_time_display_value',
            field=models.DateTimeField(help_text='Created time display value', max_length=10000, null=True, verbose_name='created_time_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_time_value',
            field=models.CharField(help_text='Created time Value', max_length=10000, null=True, verbose_name='created_time_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='department_id',
            field=models.IntegerField(help_text='Department ID', null=True, verbose_name='department_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='department_name',
            field=models.CharField(help_text='Department name', max_length=10000, null=True, verbose_name='department_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='description',
            field=models.CharField(help_text='Description', max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='email_cc',
            field=models.CharField(help_text='Email cc', max_length=10000, null=True, verbose_name='email_cc'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='email_ids_to_notify',
            field=models.CharField(help_text='Email ids to notify', max_length=10000, null=True, verbose_name='email_ids_to_notify'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='email_to',
            field=models.CharField(help_text='Requester ID', max_length=10000, null=True, verbose_name='email_to'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='first_response_due_by_time_display_value',
            field=models.DateTimeField(help_text='First response due by time', max_length=10000, null=True, verbose_name='first_response_due_by_time_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='first_response_due_by_time_value',
            field=models.CharField(help_text='First response due by time value', max_length=10000, null=True, verbose_name='first_response_due_by_time_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='group_id',
            field=models.IntegerField(help_text='Group Id', null=True, verbose_name='group_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='group_name',
            field=models.CharField(help_text='Group Name', max_length=10000, null=True, verbose_name='group_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_attachments',
            field=models.BooleanField(help_text='Has attachments', null=True, verbose_name='has_attachments'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_conversation',
            field=models.BooleanField(help_text='Has conversation', null=True, verbose_name='has_conversation'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_dependency',
            field=models.BooleanField(help_text='Has Dependency', null=True, verbose_name='has_dependency'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_draft',
            field=models.BooleanField(help_text='Has draft', null=True, verbose_name='has_draft'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_linked_requests',
            field=models.BooleanField(help_text='Has linked requests', null=True, verbose_name='has_linked_requests'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_notes',
            field=models.BooleanField(help_text='Has notes', null=True, verbose_name='has_notes'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_problem',
            field=models.BooleanField(help_text='Has Problem', null=True, verbose_name='has_problem'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_project',
            field=models.BooleanField(help_text='Has Project', null=True, verbose_name='has_project'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_request_initiated_change',
            field=models.BooleanField(help_text='Has request initiated change', null=True, verbose_name='has_request_initiated_change'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='has_resolution_attachments',
            field=models.BooleanField(help_text='Resolution Attachments', null=True, verbose_name='has_resolution_attachments'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='impact_details',
            field=models.CharField(help_text='Impact Details', max_length=10000, null=True, verbose_name='impact_details'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='impact_id',
            field=models.IntegerField(help_text='Impact Id', null=True, verbose_name='impact_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='impact_name',
            field=models.CharField(help_text='Impact Name', max_length=10000, null=True, verbose_name='impact_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_billable',
            field=models.BooleanField(help_text='Is billable', null=True, verbose_name='is_billable'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_fcr',
            field=models.BooleanField(help_text='Is fcr', null=True, verbose_name='is_fcr'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_reopened',
            field=models.BooleanField(help_text='Is reopenend', null=True, verbose_name='is_reopened'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_request_contract_applicable',
            field=models.BooleanField(help_text='Request contrat applicable', null=True, verbose_name='is_request_contract_applicable'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_service_request',
            field=models.BooleanField(help_text='Is service Request', null=True, verbose_name='is_service_request'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_shared',
            field=models.BooleanField(help_text='Is shared', null=True, verbose_name='is_shared'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='is_trashed',
            field=models.BooleanField(help_text='Is trashed', null=True, verbose_name='is_trashed'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='item',
            field=models.CharField(help_text='Item', max_length=10000, null=True, verbose_name='item'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='itsm_id',
            field=models.CharField(help_text='Id', max_length=10000, null=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='last_updated_time_display_value',
            field=models.DateTimeField(help_text='Last updated time', max_length=10000, null=True, verbose_name='last_updated_time_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='last_updated_time_value',
            field=models.CharField(help_text='Last updated time value', max_length=10000, null=True, verbose_name='last_updated_time_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='level_id',
            field=models.IntegerField(help_text='Level id', null=True, verbose_name='level_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='level_name',
            field=models.CharField(help_text='Level Name', max_length=10000, null=True, verbose_name='level_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='lifecycle',
            field=models.CharField(help_text='Lifecycle', max_length=10000, null=True, verbose_name='lifecycle'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='linked_to_request',
            field=models.CharField(help_text='Linked Request', max_length=10000, null=True, verbose_name='linked_to_request'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='mode',
            field=models.CharField(help_text='Mode', max_length=10000, null=True, verbose_name='mode'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='mode_id',
            field=models.IntegerField(help_text='Mode id', null=True, verbose_name='mode_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='mode_name',
            field=models.CharField(help_text='Mode name', max_length=10000, null=True, verbose_name='mode_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='priority_color',
            field=models.CharField(help_text='Priority color', max_length=10000, null=True, verbose_name='priority_color'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='priority_id',
            field=models.IntegerField(help_text='Priority Id', null=True, verbose_name='priority_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='priority_name',
            field=models.CharField(help_text='Priority Name', max_length=10000, null=True, verbose_name='priority_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='request_template_task_ids',
            field=models.CharField(help_text='Request template task ids', max_length=10000, null=True, verbose_name='request_template_task_ids'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='request_type_id',
            field=models.IntegerField(help_text='Request type id', null=True, verbose_name='request_type_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='request_type_name',
            field=models.CharField(help_text='Request type name', max_length=10000, null=True, verbose_name='request_type_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='requester_email_id',
            field=models.CharField(help_text='Requester Email Id', max_length=10000, null=True, verbose_name='requester_email_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='requester_id',
            field=models.IntegerField(help_text='Requester ID', null=True, verbose_name='requester_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='requester_is_vipuser',
            field=models.BooleanField(help_text='Requester vipuser', null=True, verbose_name='requester_is_vipuser'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='requester_mobile',
            field=models.CharField(help_text='Requester Mobile', max_length=10000, null=True, verbose_name='requester_mobile'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='requester_name',
            field=models.CharField(help_text='Requester name', max_length=10000, null=True, verbose_name='requester_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='requester_status',
            field=models.CharField(help_text='Requester Status', max_length=10000, null=True, verbose_name='requester_status'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_content',
            field=models.CharField(help_text='Resolution Content', max_length=10000, null=True, verbose_name='resolution_content'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_resolution_attachments',
            field=models.CharField(help_text='Resolution on Attachment', max_length=10000, null=True, verbose_name='resolution_resolution_attachments'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_by_email_id',
            field=models.CharField(help_text='Resolution on Email id', max_length=10000, null=True, verbose_name='resolution_submitted_by_email_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_by_id',
            field=models.CharField(help_text='Resolution by id', max_length=10000, null=True, verbose_name='resolution_submitted_by_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_by_is_vipuser',
            field=models.CharField(help_text='Resolution on vipuser', max_length=10000, null=True, verbose_name='resolution_submitted_by_is_vipuser'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_by_mobile',
            field=models.CharField(help_text='Resolution on Mobile', max_length=10000, null=True, verbose_name='resolution_submitted_by_mobile'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_by_name',
            field=models.CharField(help_text='Resolution on name', max_length=10000, null=True, verbose_name='resolution_submitted_by_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_by_status',
            field=models.CharField(help_text='Resolution on Status', max_length=10000, null=True, verbose_name='resolution_submitted_by_status'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_on_display_value',
            field=models.DateTimeField(help_text='Resolution on display value', max_length=10000, null=True, verbose_name='resolution_submitted_on_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolution_submitted_on_value',
            field=models.CharField(help_text='Resolution on value', max_length=10000, null=True, verbose_name='resolution_submitted_on_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolved_time_display_value',
            field=models.DateTimeField(help_text='Resolved time display value', max_length=10000, null=True, verbose_name='resolved_time_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='resolved_time_value',
            field=models.CharField(help_text='Resolved time value', max_length=10000, null=True, verbose_name='resolved_time_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='service_category_id',
            field=models.IntegerField(help_text='Service Category Id', null=True, verbose_name='service_category_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='service_category_name',
            field=models.CharField(help_text='Service Category Name', max_length=10000, null=True, verbose_name='service_category_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='site_id',
            field=models.IntegerField(help_text='Site ID', null=True, verbose_name='site_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='site_name',
            field=models.CharField(help_text='Site Name', max_length=10000, null=True, verbose_name='site_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='sla_id',
            field=models.IntegerField(help_text='SLA Id', null=True, verbose_name='sla_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='status_color',
            field=models.CharField(help_text='Status Color', max_length=10000, null=True, verbose_name='status_color'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='status_id',
            field=models.IntegerField(help_text='Status id', null=True, verbose_name='status_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='status_name',
            field=models.CharField(help_text='Status name', max_length=10000, null=True, verbose_name='status_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='subcategory',
            field=models.CharField(help_text='Subcategory', max_length=10000, null=True, verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='subcategory_id',
            field=models.IntegerField(help_text='Subcategory id', null=True, verbose_name='subcategory_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='subcategory_name',
            field=models.CharField(help_text='Subcategory name', max_length=10000, null=True, verbose_name='subcategory_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='subject',
            field=models.CharField(help_text='Subject', max_length=10000, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='technician_email_id',
            field=models.CharField(help_text='Technician Email ID', max_length=10000, null=True, verbose_name='technician_email_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='technician_id',
            field=models.IntegerField(help_text='Technician id', null=True, verbose_name='technician_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='technician_mobile',
            field=models.CharField(help_text='Technician Mobile', max_length=10000, null=True, verbose_name='technician_mobile'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='technician_name',
            field=models.CharField(help_text='Technician name', max_length=10000, null=True, verbose_name='technician_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='technician_status',
            field=models.CharField(help_text='Technician Status', max_length=10000, null=True, verbose_name='technician_status'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='template_id',
            field=models.IntegerField(help_text='Template id', null=True, verbose_name='template_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='template_name',
            field=models.CharField(help_text='Template name', max_length=10000, null=True, verbose_name='template_name'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='time_elapsed_display_value',
            field=models.DateTimeField(help_text='Time elapsed display value', max_length=10000, null=True, verbose_name='time_elapsed_display_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='time_elapsed_value',
            field=models.CharField(help_text='Time elapsed value', max_length=10000, null=True, verbose_name='time_elapsed_value'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='udf_fields_udf_long_3302',
            field=models.CharField(help_text='UDF Fields udf sline 3302', max_length=10000, null=True, verbose_name='udf_fields_udf_long_3302'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='udf_fields_udf_long_4502',
            field=models.CharField(help_text='Udf fields udf long 4502', max_length=10000, null=True, verbose_name='udf_fields_udf_long_4502'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='udf_fields_udf_sline_4501',
            field=models.CharField(help_text='Udf fields', max_length=10000, null=True, verbose_name='udf_fields_udf_sline_4501'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='udf_fields_udf_sline_5401',
            field=models.CharField(help_text='UDF Fields udf sline 5401', max_length=10000, null=True, verbose_name='udf_fields_udf_sline_5401'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='urgency_id',
            field=models.IntegerField(help_text='Urgency Id', null=True, verbose_name='urgency_id'),
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='urgency_name',
            field=models.CharField(help_text='Urgency Name', max_length=10000, null=True, verbose_name='urgency_name'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='category_id',
            field=models.IntegerField(help_text='Category id', null=True, verbose_name='category_id'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='due_by_time',
            field=models.DateTimeField(help_text='Due by time', max_length=10000, null=True, verbose_name='due_by_time'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='is_first_response_overdue',
            field=models.BooleanField(help_text='Is first response overdue', null=True, verbose_name='is_first_response_overdue'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='is_overdue',
            field=models.BooleanField(help_text='Is overdue', null=True, verbose_name='is_overdue'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='sla_name',
            field=models.CharField(help_text='SLA Name', max_length=10000, null=True, verbose_name='sla_name'),
        ),
        migrations.DeleteModel(
            name='HistoricalSTG_ITSM',
        ),
    ]
