# Generated by Django 4.0 on 2022-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0003_remove_stg_itsm_account_remove_stg_itsm_affair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_siem',
            name='assigned_to',
            field=models.CharField(help_text='Assigned To', max_length=10000, null=True, verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='categories',
            field=models.CharField(help_text='Categories', max_length=10000, null=True, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='close_time',
            field=models.DateTimeField(help_text='Close Time', max_length=10000, null=True, verbose_name='close_time'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='closing_user',
            field=models.CharField(help_text='Closing User', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='description',
            field=models.CharField(help_text='Description', max_length=100000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='destination_networks',
            field=models.CharField(help_text='Destination Network', max_length=10000, null=True, verbose_name='destination_networks'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='first_persisted_time',
            field=models.DateTimeField(help_text='first_persisted_time', max_length=10000, null=True, verbose_name='first_persisted_time'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='last_persisted_time',
            field=models.DateTimeField(help_text='last_persisted_time', max_length=10000, null=True, verbose_name='last_persisted_time'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='last_updated_datetime',
            field=models.DateTimeField(help_text='Last Updated Date Time', max_length=10000, null=True, verbose_name='last_updated_datetime'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='local_destination_address_ids',
            field=models.CharField(help_text='Local destination address ids', max_length=10000, null=True, verbose_name='local_destination_address_ids'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='log_sources',
            field=models.CharField(help_text='Log Sources', max_length=10000, null=True, verbose_name='log_sources'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='offense_source',
            field=models.CharField(help_text='Offense Source', max_length=10000, null=True, verbose_name='offense_source'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='rule_details',
            field=models.CharField(help_text='rule_details', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='rule_name',
            field=models.CharField(help_text='Rule Name', max_length=10000, null=True, verbose_name='rule_name'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='rules',
            field=models.CharField(help_text='Rules', max_length=10000, null=True, verbose_name='rules'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='source_address_ids',
            field=models.CharField(help_text='Source address ids', max_length=10000, null=True, verbose_name='source_address_ids'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='source_network',
            field=models.CharField(help_text='Source Network', max_length=10000, null=True, verbose_name='source_network'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='start_datetime',
            field=models.DateTimeField(help_text='Start Date Time', max_length=10000, null=True, verbose_name='start_datetime'),
        ),
        migrations.AlterField(
            model_name='stg_siem',
            name='status',
            field=models.CharField(help_text='Status', max_length=10000, null=True, verbose_name='status'),
        ),
    ]
