# Generated by Django 4.0 on 2022-10-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0004_alter_stg_siem_assigned_to_alter_stg_siem_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_SIEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start Date', verbose_name='start_date')),
                ('end_date', models.DateField(help_text='End Date', null=True, verbose_name='end_date')),
                ('status', models.CharField(help_text='status', max_length=200, verbose_name='status')),
            ],
        ),
    ]
