# Generated by Django 4.0 on 2022-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0005_audit_siem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor_siem',
            name='log_sources',
            field=models.CharField(help_text='log_sources', max_length=10000, null=True, verbose_name='log_sources'),
        ),
    ]
