# Generated by Django 4.0 on 2022-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0006_alter_historicalextractor_itsm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor_siem',
            name='close_time',
            field=models.CharField(help_text='close_time', max_length=200, null=True, verbose_name='close_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='first_persisted_time',
            field=models.CharField(help_text='first_persisted_time', max_length=200, null=True, verbose_name='first_persisted_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='last_persisted_time',
            field=models.CharField(help_text='last_persisted_time', max_length=200, null=True, verbose_name='last_persisted_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='last_updated_time',
            field=models.CharField(help_text='last_updated_time', max_length=200, null=True, verbose_name='last_updated_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='rule_details',
            field=models.CharField(help_text='rule_details', max_length=200, null=True, verbose_name='rule_details'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='rules',
            field=models.CharField(help_text='rules', max_length=200, null=True, verbose_name='rules'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='start_time',
            field=models.CharField(help_text='start_time', max_length=200, null=True, verbose_name='start_time'),
        ),
    ]
