# Generated by Django 4.0 on 2022-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0006_alter_extractor_siem_log_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_itsm',
            name='assigned_time_display_value',
            field=models.DateTimeField(blank=True, help_text='Assigned time display value', max_length=10000, null=True, verbose_name='assigned_time_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='completed_time_display_value',
            field=models.DateTimeField(blank=True, help_text='Completed time display value', max_length=10000, null=True, verbose_name='completed_time_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='created_time_display_value',
            field=models.DateTimeField(blank=True, help_text='Created time display value', max_length=10000, null=True, verbose_name='created_time_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='due_by_time',
            field=models.DateTimeField(blank=True, help_text='Due by time', max_length=10000, null=True, verbose_name='due_by_time'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='first_response_due_by_time_display_value',
            field=models.DateTimeField(blank=True, help_text='First response due by time', max_length=10000, null=True, verbose_name='first_response_due_by_time_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='last_updated_time_display_value',
            field=models.DateTimeField(blank=True, help_text='Last updated time', max_length=10000, null=True, verbose_name='last_updated_time_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='resolution_submitted_on_display_value',
            field=models.DateTimeField(blank=True, help_text='Resolution on display value', max_length=10000, null=True, verbose_name='resolution_submitted_on_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='resolved_time_display_value',
            field=models.DateTimeField(blank=True, help_text='Resolved time display value', max_length=10000, null=True, verbose_name='resolved_time_display_value'),
        ),
        migrations.AlterField(
            model_name='stg_itsm',
            name='time_elapsed_display_value',
            field=models.DateTimeField(blank=True, help_text='Time elapsed display value', max_length=10000, null=True, verbose_name='time_elapsed_display_value'),
        ),
    ]
