# Generated by Django 4.0 on 2022-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0007_alter_stg_itsm_assigned_time_display_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(help_text='entity_id', max_length=10000, verbose_name='entity_id')),
                ('entity_name', models.CharField(help_text='entity_name', max_length=10000, verbose_name='entity_name')),
                ('entity_color', models.CharField(help_text='entity_color', max_length=10000, verbose_name='entity_color')),
                ('location_id', models.CharField(help_text='location_id', max_length=10000, verbose_name='location_id')),
                ('location_name', models.CharField(help_text='location_name', max_length=10000, verbose_name='location_name')),
                ('function_id', models.CharField(help_text='function_id', max_length=10000, verbose_name='function_id')),
                ('function_name', models.CharField(help_text='function_name', max_length=10000, verbose_name='function_name')),
                ('asset_id', models.CharField(help_text='asset_id', max_length=10000, verbose_name='asset_id')),
                ('asset_name', models.CharField(help_text='asset_name', max_length=10000, verbose_name='asset_name')),
                ('asset_type', models.CharField(help_text='asset_type', max_length=10000, verbose_name='asset_type')),
                ('asset_color', models.CharField(help_text='asset_color', max_length=10000, verbose_name='asset_color')),
                ('usecase_id', models.CharField(help_text='usecase_id', max_length=10000, verbose_name='usecase_id')),
                ('use_case', models.CharField(help_text='use_case', max_length=10000, verbose_name='use_case')),
                ('rule_id', models.CharField(help_text='rule_id', max_length=10000, verbose_name='rule_id')),
                ('rule_name', models.CharField(help_text='rule_name', max_length=10000, verbose_name='rule_name')),
                ('seim_id', models.CharField(help_text='seim_id', max_length=10000, verbose_name='seim_id')),
                ('events', models.CharField(help_text='events', max_length=10000, verbose_name='events')),
                ('starttime', models.CharField(help_text='starttime', max_length=10000, verbose_name='starttime')),
                ('endtime', models.CharField(help_text='endtime', max_length=10000, verbose_name='endtime')),
                ('description', models.CharField(help_text='description', max_length=10000, verbose_name='description')),
                ('itsm_id', models.CharField(help_text='itsm_id', max_length=10000, verbose_name='itsm_id')),
                ('status', models.CharField(help_text='status', max_length=10000, verbose_name='status')),
                ('priority', models.CharField(help_text='priority', max_length=10000, verbose_name='priority')),
                ('group', models.CharField(help_text='group', max_length=10000, verbose_name='group')),
                ('service_category', models.CharField(help_text='service_category', max_length=10000, verbose_name='service_category')),
                ('assigned_time', models.CharField(help_text='assigned_time', max_length=10000, verbose_name='assigned_time')),
                ('resolution', models.CharField(help_text='resolution', max_length=10000, verbose_name='resolution')),
                ('assets', models.CharField(help_text='assets', max_length=10000, verbose_name='assets')),
                ('site', models.CharField(help_text='site', max_length=10000, verbose_name='site')),
                ('replys', models.CharField(help_text='replys', max_length=10000, verbose_name='replys')),
                ('created_time', models.CharField(help_text='Id', max_length=10000, verbose_name='created_time')),
                ('is_overdue', models.CharField(help_text='Id', max_length=10000, verbose_name='is_overdue')),
                ('due_by_time', models.CharField(help_text='Id', max_length=10000, verbose_name='due_by_time')),
                ('first_response_due_by_time', models.CharField(help_text='first_response_due_by_time', max_length=10000, verbose_name='first_response_due_by_time')),
                ('is_first_response_overdue', models.CharField(help_text='is_first_response_overdue', max_length=10000, verbose_name='is_first_response_overdue')),
                ('impact', models.CharField(help_text='impact', max_length=10000, verbose_name='impact')),
                ('urgency', models.CharField(help_text='urgency', max_length=10000, verbose_name='urgency')),
                ('subject', models.CharField(help_text='subject', max_length=10000, verbose_name='subject')),
                ('comments', models.CharField(help_text='comments', max_length=10000, verbose_name='comments')),
                ('soar_id', models.CharField(help_text='soar_id', max_length=10000, verbose_name='soar_id')),
                ('ticket_id', models.CharField(help_text='ticket_id', max_length=10000, verbose_name='ticket_id')),
                ('Suspicious', models.CharField(help_text='Suspicious', max_length=10000, verbose_name='Suspicious')),
            ],
        ),
    ]
