# Generated by Django 4.0 on 2022-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0007_alter_extractor_siem_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor_siem',
            name='assigned_to',
            field=models.CharField(help_text='assigned_to', max_length=10000, null=True, verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='categories',
            field=models.CharField(help_text='categories', max_length=10000, null=True, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='category_count',
            field=models.CharField(help_text='category_count', max_length=10000, null=True, verbose_name='category_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='close_time',
            field=models.CharField(help_text='close_time', max_length=10000, null=True, verbose_name='close_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='closing_reason_id',
            field=models.CharField(help_text='closing_reason_id', max_length=10000, null=True, verbose_name='closing_reason_id'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='closing_user',
            field=models.CharField(help_text='closing_user', max_length=10000, null=True, verbose_name='closing_user'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='credibility',
            field=models.CharField(help_text='credibility', max_length=10000, null=True, verbose_name='credibility'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='description',
            field=models.CharField(help_text='description', max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='destination_networks',
            field=models.CharField(help_text='destination_networks', max_length=10000, null=True, verbose_name='destination_networks'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='device_count',
            field=models.CharField(help_text='device_count', max_length=10000, null=True, verbose_name='device_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='domain_id',
            field=models.CharField(help_text='domain_id', max_length=10000, null=True, verbose_name='domain_id'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='event_count',
            field=models.CharField(help_text='event_count', max_length=10000, null=True, verbose_name='event_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='first_persisted_time',
            field=models.CharField(help_text='first_persisted_time', max_length=10000, null=True, verbose_name='first_persisted_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='flow_count',
            field=models.CharField(help_text='flow_count', max_length=10000, null=True, verbose_name='flow_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='follow_up',
            field=models.CharField(help_text='follow_up', max_length=10000, null=True, verbose_name='follow_up'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='inactive',
            field=models.CharField(help_text='inactive', max_length=10000, null=True, verbose_name='inactive'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='last_persisted_time',
            field=models.CharField(help_text='last_persisted_time', max_length=10000, null=True, verbose_name='last_persisted_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='last_updated_time',
            field=models.CharField(help_text='last_updated_time', max_length=10000, null=True, verbose_name='last_updated_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='local_destination_address_ids',
            field=models.CharField(help_text='local_destination_address_ids', max_length=10000, null=True, verbose_name='local_destination_address_ids'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='local_destination_count',
            field=models.CharField(help_text='local_destination_count', max_length=10000, null=True, verbose_name='local_destination_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='log_sources',
            field=models.JSONField(help_text='log_sources', max_length=10000, null=True, verbose_name='log_sources'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='magnitude',
            field=models.CharField(help_text='magnitude', max_length=10000, null=True, verbose_name='magnitude'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='offense_source',
            field=models.CharField(help_text='offense_source', max_length=10000, null=True, verbose_name='offense_source'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='offense_type',
            field=models.CharField(help_text='offense_type', max_length=10000, null=True, verbose_name='offense_type'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='policy_category_count',
            field=models.CharField(help_text='policy_category_count', max_length=10000, null=True, verbose_name='policy_category_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='protected',
            field=models.CharField(help_text='protected', max_length=10000, null=True, verbose_name='protected'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='relevance',
            field=models.CharField(help_text='relevance', max_length=10000, null=True, verbose_name='relevance'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='remote_destination_count',
            field=models.CharField(help_text='remote_destination_count', max_length=10000, null=True, verbose_name='remote_destination_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='rule_details',
            field=models.CharField(help_text='rule_details', max_length=10000, null=True, verbose_name='rule_details'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='rules',
            field=models.CharField(help_text='rules', max_length=10000, null=True, verbose_name='rules'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='security_category_count',
            field=models.CharField(help_text='security_category_count', max_length=10000, null=True, verbose_name='security_category_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='severity',
            field=models.CharField(help_text='severity', max_length=10000, null=True, verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='siem_id',
            field=models.CharField(help_text='id', max_length=10000, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='source_address_ids',
            field=models.CharField(help_text='source_address_ids', max_length=10000, null=True, verbose_name='source_address_ids'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='source_count',
            field=models.CharField(help_text='source_count', max_length=10000, null=True, verbose_name='source_count'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='source_network',
            field=models.CharField(help_text='source_network', max_length=10000, null=True, verbose_name='source_network'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='start_time',
            field=models.CharField(help_text='start_time', max_length=10000, null=True, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='status',
            field=models.CharField(help_text='status', max_length=10000, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='extractor_siem',
            name='username_count',
            field=models.CharField(help_text='username_count', max_length=10000, null=True, verbose_name='username_count'),
        ),
    ]
