# Generated by Django 4.0 on 2022-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0008_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='endtime',
            field=models.DateTimeField(help_text='endtime', max_length=10000, verbose_name='endtime'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='starttime',
            field=models.DateTimeField(help_text='starttime', max_length=10000, verbose_name='starttime'),
        ),
    ]
