# Generated by Django 4.0 on 2022-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0009_alter_fact_endtime_alter_fact_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_ITSM_STG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start Date', verbose_name='start_date')),
                ('end_date', models.DateTimeField(help_text='End Date', null=True, verbose_name='end_date')),
                ('status', models.CharField(help_text='status', max_length=200, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_SIEM_STG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start Date', verbose_name='start_date')),
                ('end_date', models.DateTimeField(help_text='End Date', null=True, verbose_name='end_date')),
                ('status', models.CharField(help_text='status', max_length=200, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_SOAR_EXTRACTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start Date', verbose_name='start_date')),
                ('end_date', models.DateTimeField(help_text='End Date', null=True, verbose_name='end_date')),
                ('status', models.CharField(help_text='status', max_length=200, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Audit_SOAR_STG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Start Date', verbose_name='start_date')),
                ('end_date', models.DateTimeField(help_text='End Date', null=True, verbose_name='end_date')),
                ('status', models.CharField(help_text='status', max_length=200, verbose_name='status')),
            ],
        ),
    ]
