# Generated by Django 4.0 on 2022-10-10 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0010_audit_itsm_stg_audit_siem_stg_audit_soar_extractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractor_itsm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created at', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractor_siem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created at', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractor_soar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created at', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stg_itsm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created at', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stg_siem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created at', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stg_soar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='created at', verbose_name='created at'),
            preserve_default=False,
        ),
    ]
