# Generated by Django 4.0 on 2022-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0011_extractor_itsm_created_at_extractor_siem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractor_soar',
            name='ClosingTime',
        ),
    ]
