# Generated by Django 4.0 on 2022-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0012_remove_extractor_soar_closingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractor_soar',
            name='ClosingTime',
            field=models.CharField(help_text='Closing Time', max_length=2000, null=True, verbose_name='ClosingTime'),
        ),
    ]
