# Generated by Django 4.0 on 2022-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0013_extractor_soar_closingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stg_siem',
            name='asset',
            field=models.CharField(help_text='Asset_name', max_length=200, null=True),
        ),
    ]
