# Generated by Django 4.0 on 2022-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0015_alter_stg_siem_log_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_siem',
            name='log_sources',
            field=models.CharField(help_text='Log Sources', max_length=10000, null=True, verbose_name='log_sources'),
        ),
    ]
