# Generated by Django 4.0 on 2022-10-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0016_alter_stg_siem_log_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_soar',
            name='TicketIDs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sita.stg_siem', verbose_name='TicketIDs'),
        ),
    ]
