# Generated by Django 4.0 on 2022-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0019_stg_itsm_soar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_itsm',
            name='end_date',
            field=models.DateTimeField(help_text='End Date', null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='audit_itsm',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date', verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='audit_siem',
            name='end_date',
            field=models.DateTimeField(help_text='End Date', null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='audit_siem',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date', verbose_name='start_date'),
        ),
    ]
