# Generated by Django 4.0 on 2022-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0021_alter_fact_suspicious_alter_fact_asset_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit_itsm',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date', null=True, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='audit_siem',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date', null=True, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='audit_soar_extractor',
            name='start_date',
            field=models.DateTimeField(help_text='Start Date', null=True, verbose_name='start_date'),
        ),
    ]
