# Generated by Django 4.0 on 2022-10-12 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0022_alter_audit_itsm_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor_itsm',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='created at', verbose_name='created at'),
        ),
    ]
