# Generated by Django 4.0 on 2022-10-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0024_stg_siem_asset_type_alter_extractor_siem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stg_siem',
            name='asset_id',
            field=models.CharField(help_text='Asset_id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stg_siem',
            name='asset_type_id',
            field=models.CharField(help_text='Asset_type_id', max_length=200, null=True),
        ),
    ]
