# Generated by Django 4.0 on 2022-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0025_stg_siem_asset_id_stg_siem_asset_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_itsm',
            name='no_dump_data',
            field=models.IntegerField(help_text='no_dump_data', null=True, verbose_name='no_dump_data'),
        ),
        migrations.AddField(
            model_name='audit_itsm_stg',
            name='no_dump_data',
            field=models.IntegerField(help_text='no_dump_data', null=True, verbose_name='no_dump_data'),
        ),
        migrations.AddField(
            model_name='audit_siem',
            name='no_dump_data',
            field=models.IntegerField(help_text='no_dump_data', null=True, verbose_name='no_dump_data'),
        ),
        migrations.AddField(
            model_name='audit_siem_stg',
            name='no_dump_data',
            field=models.IntegerField(help_text='no_dump_data', null=True, verbose_name='no_dump_data'),
        ),
        migrations.AddField(
            model_name='audit_soar_extractor',
            name='no_dump_data',
            field=models.IntegerField(help_text='no_dump_data', null=True, verbose_name='no_dump_data'),
        ),
        migrations.AddField(
            model_name='audit_soar_stg',
            name='no_dump_data',
            field=models.IntegerField(help_text='no_dump_data', null=True, verbose_name='no_dump_data'),
        ),
    ]
