# Generated by Django 4.0 on 2022-10-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0028_audit_itsm_total_data_audit_itsm_stg_total_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsdetails',
            name='asset_color',
            field=models.CharField(help_text='asset_color', max_length=50, null=True, verbose_name='asset_color'),
        ),
        migrations.AddField(
            model_name='assetsdetails',
            name='entity_color',
            field=models.CharField(help_text='entity_color', max_length=50, null=True, verbose_name='entity_color'),
        ),
    ]
