# Generated by Django 4.0 on 2022-10-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sita', '0029_assetsdetails_asset_color_assetsdetails_entity_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact_insights',
            name='criticality',
        ),
        migrations.RemoveField(
            model_name='fact_insights',
            name='criticality_color',
        ),
        migrations.RemoveField(
            model_name='fact_insights',
            name='last_updated_datetime',
        ),
        migrations.RemoveField(
            model_name='fact_insights',
            name='magnitude',
        ),
        migrations.RemoveField(
            model_name='fact_insights',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='fact_insights',
            name='target',
        ),
        migrations.AddField(
            model_name='fact_insights',
            name='comments',
            field=models.CharField(help_text='comments', max_length=10000, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='Suspicious',
            field=models.CharField(help_text='Suspicious', max_length=10000, null=True, verbose_name='Suspicious'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='asset_color',
            field=models.CharField(help_text='asset_color', max_length=10000, null=True, verbose_name='asset_color'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='asset_id',
            field=models.CharField(help_text='asset_id', max_length=10000, null=True, verbose_name='asset_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='asset_name',
            field=models.CharField(help_text='asset_name', max_length=10000, null=True, verbose_name='asset_name'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='asset_type',
            field=models.CharField(help_text='asset_type', max_length=10000, null=True, verbose_name='asset_type'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='assets',
            field=models.CharField(help_text='assets', max_length=10000, null=True, verbose_name='assets'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='assigned_time',
            field=models.CharField(help_text='assigned_time', max_length=10000, null=True, verbose_name='assigned_time'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='created_time',
            field=models.CharField(help_text='Id', max_length=10000, null=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='description',
            field=models.CharField(help_text='description', max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='due_by_time',
            field=models.CharField(help_text='Id', max_length=10000, null=True, verbose_name='due_by_time'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='endtime',
            field=models.DateTimeField(help_text='endtime', max_length=10000, null=True, verbose_name='endtime'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='entity_color',
            field=models.CharField(help_text='entity_color', max_length=10000, null=True, verbose_name='entity_color'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='entity_id',
            field=models.CharField(help_text='entity_id', max_length=10000, null=True, verbose_name='entity_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='entity_name',
            field=models.CharField(help_text='entity_name', max_length=10000, null=True, verbose_name='entity_name'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='events',
            field=models.CharField(help_text='events', max_length=10000, null=True, verbose_name='events'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='first_response_due_by_time',
            field=models.CharField(help_text='first_response_due_by_time', max_length=10000, null=True, verbose_name='first_response_due_by_time'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='function_id',
            field=models.CharField(help_text='function_id', max_length=10000, null=True, verbose_name='function_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='function_name',
            field=models.CharField(help_text='function_name', max_length=10000, null=True, verbose_name='function_name'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='group',
            field=models.CharField(help_text='group', max_length=10000, null=True, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='impact',
            field=models.CharField(help_text='impact', max_length=10000, null=True, verbose_name='impact'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='is_first_response_overdue',
            field=models.CharField(help_text='is_first_response_overdue', max_length=10000, null=True, verbose_name='is_first_response_overdue'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='is_overdue',
            field=models.CharField(help_text='Id', max_length=10000, null=True, verbose_name='is_overdue'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='itsm_id',
            field=models.CharField(help_text='itsm_id', max_length=10000, null=True, verbose_name='itsm_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='location_id',
            field=models.CharField(help_text='location_id', max_length=10000, null=True, verbose_name='location_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='location_name',
            field=models.CharField(help_text='location_name', max_length=10000, null=True, verbose_name='location_name'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='priority',
            field=models.CharField(help_text='priority', max_length=10000, null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='replys',
            field=models.CharField(help_text='replys', max_length=10000, null=True, verbose_name='replys'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='rule_id',
            field=models.CharField(help_text='rule_id', max_length=10000, null=True, verbose_name='rule_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='rule_name',
            field=models.CharField(help_text='rule_name', max_length=10000, null=True, verbose_name='rule_name'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='seim_id',
            field=models.CharField(help_text='seim_id', max_length=10000, null=True, verbose_name='seim_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='service_category',
            field=models.CharField(help_text='service_category', max_length=10000, null=True, verbose_name='service_category'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='site',
            field=models.CharField(help_text='site', max_length=10000, null=True, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='soar_id',
            field=models.CharField(help_text='soar_id', max_length=10000, null=True, verbose_name='soar_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='starttime',
            field=models.DateTimeField(help_text='starttime', max_length=10000, null=True, verbose_name='starttime'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='status',
            field=models.CharField(help_text='status', max_length=10000, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='subject',
            field=models.CharField(help_text='subject', max_length=10000, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='ticket_id',
            field=models.CharField(help_text='ticket_id', max_length=10000, null=True, verbose_name='ticket_id'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='urgency',
            field=models.CharField(help_text='urgency', max_length=10000, null=True, verbose_name='urgency'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='use_case',
            field=models.CharField(help_text='use_case', max_length=10000, null=True, verbose_name='use_case'),
        ),
        migrations.AlterField(
            model_name='fact_insights',
            name='usecase_id',
            field=models.CharField(help_text='usecase_id', max_length=10000, null=True, verbose_name='usecase_id'),
        ),
    ]
